---
###
### Based on the manual update instructions on Pterodactyl's documentation:
### https://pterodactyl.io/panel/1.0/updating.html
###

- name: Update Pterodactyl Panel
  hosts: all
  become: true

  vars:
    release_url: "https://github.com/pterodactyl/panel/releases/latest/download/panel.tar.gz"  # Usually stick to latest

    panel_path: /var/www/pterodactyl

    # 'www-data' if using NGINX or Apache (not on CentOS)  //  'nginx' if using NGINX on CentOS  //  'apache' if using Apache on CentOS
    web_user: www-data
    web_group: www-data


  tasks:

    ### Enter Maintenance Mode
    - name: Enter maintenance mode
      command: php artisan down
      args:
        chdir: "{{ panel_path }}"


    ### Download the Update
    - name: Download latest panel release
      ansible.builtin.get_url:
        url: "{{ release_url }}"
        dest: "/tmp/panel.tar.gz"
        mode: "0644"

    - name: Extract panel release
      ansible.builtin.unarchive:
        src: "/tmp/panel.tar.gz"
        dest: "{{ panel_path }}"
        remote_src: true  # Unpacks archive as it already exists on the target with prior task.

    - name: Fix permissions for storage and cache
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "0755"
        recurse: true
      loop:
        - "{{ panel_path }}/storage"
        - "{{ panel_path }}/bootstrap/cache"

    - name: Delete the downloaded .tar.gz file
      ansible.builtin.file:
        path: "/tmp/panel.tar.gz"
        state: absent


    ### Update Dependencies
    - name: Install composer dependencies
      command: composer install --no-dev --optimize-autoloader
      args:
        chdir: "{{ panel_path }}"


    ### Clear Compiled Template Cache
    - name: Clear compiled template cache
      command: "{{ item }}"
      args:
        chdir: "{{ panel_path }}"
      loop:
        - php artisan view:clear
        - php artisan config:clear


    ### Database Updates
    - name: Run database migrations & seed
      command: php artisan migrate --seed --force
      args:
        chdir: "{{ panel_path }}"


    ### Set Permissions
    - name: Set correct ownership for panel files
      ansible.builtin.file:
        path: "{{ panel_path }}"
        owner: "{{ web_user }}"
        group: "{{ web_group }}"
        recurse: true


    ### Restarting Queue Workers
    - name: Restart queue workers
      command: php artisan queue:restart
      args:
        chdir: "{{ panel_path }}"


    ### Exit Maintenance Mode
    - name: Exit maintenance mode
      command: php artisan up
      args:
        chdir: "{{ panel_path }}"
